# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateTimeField(default=menu.models.set_expiry_date),
        ),
    ]
