# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-27 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190826_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-expiration_date']},
        ),
    ]
